### ISSUE TITLE
App download snippet should reflect chosen version

### ISSUE THREAD

**Issue by ericsampson** [MehediH/winstall#63] opened 2021-05-26 18:56 UTC
Hi, I noticed that when you change the version selection on an app page, the download snippet isn't updated to match.

I'm not a front-end dev, or I'd submit a PR.

Thanks!

**Comment by MehediH** [comment] 2021-05-28 14:13
Hi, I am unable to reproduce this. The version is changing as expected on my end. Could you please provide the exact reproduction steps?

**Comment by ericsampson** [comment] 2021-05-28 15:55
Hmm, I just went and verified again in both Firefox and Chrome.

1) Go to any individual app install page, in this case [Firefox](https://winstall.app/apps/Mozilla.Firefox)
2) Change the version selector from the default (latest) to any other version
3) Notice that the install snippet text isn't updated to add the chosen version (`winget install --id=Foo -e -v 75.0`)

![image](https://user-images.githubusercontent.com/1183853/120010550-e30fc200-bfa2-11eb-8b85-423d1e57425d.png)

**Comment by MehediH** [comment] 2021-05-31 14:05
Should be fixed now :)

**Closed by MehediH** 2021-05-31 14:05 UTC

**Comment by ericsampson** [comment] 2021-05-31 21:48
Thanks!
